### ISSUE TITLE
⭐️⭐️⭐️⭐️⭐️ New structure ⭐️⭐️⭐️⭐️⭐️

### ISSUE THREAD

**Issue by nedayeweb** [clonerdev/WooCommerce-Guest-Order-Sync#1]
This project with a new structure will soon be placed in a separate repository.
The new structure will be specific to WooCommerce and this project will remain because it is not specific to WooCommerce and will be specific to all stores (WooCommerce and non-WooCommerce).

**Comment by clonerdev** [comment]
👨‍💻👍🏻
